version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  wp:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wp
    volumes:
      - ./www/dmesg.app/:/var/www/html

  webp:
    image: webpsh/webps
    restart: always
    volumes:
      - ./webp_cache/:/opt/exhaust
      - ./www/dmesg.app/:/opt/pics

  nginx:
    image: nginx:alpine
#    volumes:
#      - ./conf:/etc/nginx/conf.d
#      - ./logs:/var/log/nginx/
#      - /etc/letsencrypt/live/:/etc/nginx/certs/
    ports:
      - 80:80
      - 443:443